all:
	$(MAKE) -C pdk all
	$(MAKE) -C triangle all
	$(MAKE) -C triangle-gasp all
	$(MAKE) -C triangle_strip all
	$(MAKE) -C sprite all

clean:
	$(MAKE) -C pdk clean
	$(MAKE) -C triangle clean
	$(MAKE) -C triangle-gasp clean
	$(MAKE) -C triangle_strip clean
	$(MAKE) -C sprite clean