SUBDIRS = pdk sprite triangle triangle-gasp triangle_strip

all:
	$(MAKE) -C pdk
	$(MAKE) -C sprite
	$(MAKE) -C triangle
	$(MAKE) -C triangle-gasp
	$(MAKE) -C triangle_strip

clean:
	$(MAKE) -C pdk clean
	$(MAKE) -C sprite clean
	$(MAKE) -C triangle clean
	$(MAKE) -C triangle-gasp clean
	$(MAKE) -C triangle_strip clean
